### ISSUE TITLE
Error in importing theme css

### ISSUE THREAD

**Issue by rrameshbtech** [blocknotes/activeadmin_medium_editor#3]
Hi,

I have used medium editor with default theme. It works well in my machine locally. But when I push my changes to staging environment (Heroku). The theme is not getting applied. and in developer console it shows 404 error when trying to download default.css file.

Then I removed `.css` from import statement. It is working in both local & staging environment.

I have also noticed that the last change to readme is reverse of this change.

which one is correct?
`@import 'activeadmin/medium_editor/themes/default.css';`
or 
`@import 'activeadmin/medium_editor/themes/default';` (Working for me)

**Comment by blocknotes** [comment]
@rrameshbtech the problem seems related to a bug in libsass:
https://stackoverflow.com/questions/7111610/import-regular-css-file-in-scss-file/30279590
So it should depend on the version of the sass compiler.
Are you using sassc or libsass? What version?

**Comment by blocknotes** [comment]
No more updates on this. I'm closing it
